version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: local-mongodb
    restart: always
    ports:
      - "27017:27017" # Expose MongoDB on localhost:27017
    volumes:
      - mongodb_data:/data/db # Persistent storage for MongoDB

  postgresql:
    container_name: local-postgre
    image: postgres:15.5
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=latihan
    ports:
      - "5432:5432"
    volumes:
      - mongodb_data:/var/lib/postgresql/data
      
volumes:
  mongodb_data:
    driver: local